version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
before_build:
- ps: nuget restore NetStorage.sln
build:
  project: NetStorage.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://vimond.artifactoryonline.com/vimond/api/nuget/nuget-releases-local
  api_key:
    secure: hFoOZlP6f0aiAt/2IkHySQNx7cVKZjB1kDJ8kyFE2vksTrKcYrDkC4tXI++HmNNq
  skip_symbols: true
  artifact: /.*\.nupkg/